name: Roy AsciiDoc push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: generate asciidoc
        run: |
          hostname
          pwd
          touch xx
          ls -l
